### PR TITLE
#170947679 Send notification to the manager when request is edited

### PR DESCRIPTION
**Pull request by EugeneMunya**
#### What does this PR do?
- Send notification to the user and his/her manager when a request is modified
#### Description of Task to be completed?
- When a requester modifies something on the trip request he/she has made, notification will be
pop up and notification panel will be updated to both requester and his/ her manager, the notification will be clickable and redirect the user to the edited trip request.

#### How should this be manually tested?
- open your terminal and run this command `git clone https://github.com/andela/knightsbn    backend.git` to clone repository
- run `cd knights-bn-backend` to get inside the project
- run `git fetch && git checkout ft-recieve-notification-when-edit-170947679` 
- run `npm install` to install dependencies
- check if you have PostgresQL database if you don't have it install it from here [PostgreSQL](https://www.2ndquadrant.com/en/blog/pginstaller-install-postgresql/)
- create database
- create `.env` file in your project root directory
- follow `env.example` file to create environment variables in `.env` file and 
   assign them with all your database configurations 
- run `npm run createTables` to create tables in the new database you have created.
- run `npm run dev-start` to start the server.
- open your postman or any other API tester you have and use this URL to login `http://localhost:4000/api/v1/auth/login` and down below there is a default user you can use
```
{
   "email": "alain.maxime@gmail.com",
    "password": "Niyonkuru@1"
}
```
- open this URL in your browser `http://localhost:4000/client/editRequest.html`
allow notification permission first by clicking on allow button on the browser alert which looks like below image 
Screen Shot 2020-03-17 at 07 56 30

 and see on the left side of the page, all your trip requests and choose one of them and update it by filling that form on that page.

- After filling the form click the send button and you will see the notification popping up and left side column will be updated, once you click on the notification you will be redirected to the modified trip request.

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#170947679](https://www.pivotaltracker.com/story/show/170947679)
#### Notification
Screen Shot 2020-03-13 at 09 34 38

#### Update notification panel
Screen Shot 2020-03-13 at 09 14 45

#### Redirect to the trip request
Screen Shot 2020-03-13 at 09 26 12

### CODE REVIEW

**Comment by T2Wil** [comment]
nice work @EugeneMunya , 
After sending the request to modify the request I successfully received the link as response and even received an email as my email was set to be of admin. Unfortunately, the link provided in the response is said to be invalid.
image

The reason is only that you used `https` protocol before localhost. Fix it by replacing it with `http`

image

image

**Comment by T2Wil** [comment]
@EugeneMunya , You need to fix this:
As a user, there are some of the request fields I shouldn't be able to edit like `id, requesterId, managerId, status, createdAt,updatedAt ....`

The screenshots below demonstrate the bug where a user can edit the `status` of the request `from pending to rejected`.

image

image

**Comment by Niyonsengaeric** [comment]
@EugeneMunya  I am sending an empty object then I find this result. maybe you could add some validations 
Screen Shot 2020-03-06 at 12 13 14

**Comment by EugeneMunya** [comment]
> nice work @EugeneMunya ,
> After sending the request to modify the request I successfully received the link as response and even received an email as my email was set to be of admin. Unfortunately, the link provided in the response is said to be invalid.
> image
> 
> The reason is only that you used `https` protocol before localhost. Fix it by replacing it with `http`
> 
> image
> 
> image

I referenced the HOST_URL  variable from our `.env` file which is heroku url, you have to update you `.env` file

**Comment by EugeneMunya** [comment]
> @EugeneMunya I am sending an empty object then I find this result. maybe you could add some validations
> Screen Shot 2020-03-06 at 12 13 14

I added the validations now everything is working fine, check

**Pull request closed without merging**
