### PR TITLE
#170947662 Reset user password via email

### PR DESCRIPTION
**Pull request by Niyonsengaeric**
#### What does this PR do?
 This PR ensures that the user can restore his/her password using email. 
#### Description of Task to be completed?
- once a user forgets his login credentials, he will be able to reset his password using the email he used to create his account in the system.
- test the endpoint
- Document feature using swagger

#### How should this be manually tested?
- run `git clone https://github.com/andela/knights-bn-backend.git` to clone the repo.
- run `cd knights-bn-backend` in your terminal
- run `git checkout ft-reset-password-170947661` to switch to this branch.
- run `npm install` to install dependencies.
- create a Postgres database.
- create a SendGrid account.
- create an API key under settings on   `API Keys`
```
- create an API key under settings on   `API Keys`
- click create API key then give it a name `BN_API_KEY`
- select Restricted access 
- scroll down where it is written Mail send then give it full access.
- scroll down then click on Create and View.
- then you will see an API key 
```
- create a .env file then add environment variable as shown below:
```
DB_USER='name of the user of the database'
DB_PASS='password of your Postgres'
DB_NAME='name of the database || Barefoot'
DB_TEST_NAME='name of the database for test || Barefoot_test'
NODE_ENV='development'
SECRETKEY='PrivateKey'
BN_API_KEY='use the SendGrid given ken'
```
- run `npm run createTables` to create the database tables.
- run `npm start` to start the server.
- open the browser use URL:`http://localhost:4000/api/v1/docs/#/User/Signup` for swagger documentation.
- Open postman and copy this URL POST `localhost:4000/api/v1/reset_pw/user`
- Add a comment body in the format shown below:
```
{
	"email": "the email of the password you want to recover",
}
```
- An email containing a link for resetting will be sent to the provided email, use the link before one hour. 
- Open postman PATCH `paste the link given in email`
- Add a comment body in the format shown below:
```
{
	"newPassword": "enter the new password",
         "confirmPassword": "confirm the new password",
}
```
- You Will see a message ` "message": "Password changed successfully" ` when the password is successfully changed.
#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#170947661](https://www.pivotaltracker.com/story/show/170947661)

#### Screenshots

  ##Resetting password
 
      Password reset link sent successfully 

email send success

      Strong password required on the new password creation.

invalid password 422

      Confirmation password must match with the new password

confirmation not match

      Password successfully changed.

password  success

### CODE REVIEW

**Comment by T2Wil** [comment]
Hello @Niyonsengaeric , 
in the PR description on creating sendGrid account, the way of receiving token is not described.
I think a step for getting the token is missing!

**Comment by Niyonsengaeric** [comment]
> Hello @Niyonsengaeric ,
> in the PR description on creating sendGrid account, the way of receiving token is not described.
> I think a step to get the token is missing!

hey @T2Wil you can now try it again, I have put all the necessary steps.

**Comment by T2Wil** [comment]
> > Hello @Niyonsengaeric ,
> > in the PR description on creating sendGrid account, the way of receiving token is not described.
> > I think a step to get the token is missing!
> 
> hey @T2Wil you can now try it again, I have put all the necessary steps.

hey @Niyonsengaeric , I have tried it, but it doesn't work.
However with the key `shared on slack channel` I get the reset link in my email.

**Review by Moise1 — APPROVED** [review]

**Comment by Niyonsengaeric** [comment]
> > > Hello @Niyonsengaeric ,
> > > in the PR description on creating sendGrid account, the way of receiving token is not described.
> > > I think a step to get the token is missing!
> > 
> > 
> > hey @T2Wil you can now try it again, I have put all the necessary steps.
> 
> hey @Niyonsengaeric , I have tried it, but it doesn't work.
> However with the key `shared on slack channel` I get the reset link in my email.

@T2Wil  check the name of the key you have created it may be the problem, rename it `BN_API_KEY`

**Comment by T2Wil** [comment]
@Niyonsengaeric , 
I am assuming this error was thrown due to the weak password I have entered, I suggest to put the validation rules in the error message that could help a user form a strong password.....
 otherwise by adding numbers at the end the password is reset.
 Good job @Niyonsengaeric !

image

**Comment by T2Wil** [comment]
> > > > Hello @Niyonsengaeric ,
> > > > in the PR description on creating sendGrid account, the way of receiving token is not described.
> > > > I think a step to get the token is missing!
> > > 
> > > 
> > > hey @T2Wil you can now try it again, I have put all the necessary steps.
> > 
> > 
> > hey @Niyonsengaeric , I have tried it, but it doesn't work.
> > However with the key `shared on slack channel` I get the reset link in my email.
> 
> @T2Wil check the name of the key you have created it may be the problem, rename it `BN_API_KEY`

I think I had it set right @Niyonsengaeric .
image

**Comment by Niyonsengaeric** [comment]
> @Niyonsengaeric ,
> I am assuming this error was thrown due to the weak password I have entered, I suggest to put the validation rules in the error message that could help a user form a strong password.....
> otherwise by adding numbers at the end the password is reset.
> Good job @Niyonsengaeric !
> 
> image

thx @T2Wil for this feedback. You can now pull and try it again

**Review by T2Wil — APPROVED** [review]

**Review by MuhanguziDavid — APPROVED** [review]

**Pull request merged**
