### PR TITLE
170947680 - Send Notification for Posted Comments

### PR DESCRIPTION
**Pull request by Moise1**
#### What does this PR do?

- Notify a user when a new comment is made on the request.

#### Description of Task to be completed?

- A manager should post a comment on a request
- A requester should see a notification on a posted comment

#### How should this be manually tested?
- run `git clone https://github.com/andela/knights-bn-backend.git` to clone the repo.
- run `cd knights-bn-backend` in your terminal to enter into the repository.
- run `git checkout ft-notifications-for-comments-170947680 ` to switch to this branch.
- run `npm install` to install dependencies.
- go to this link to see live notification `https://codepen.io/moise1/pen/jOPYveW`
- create a .env file then add environment variable as shown in ` .env.example`,  check our slack channel `code-knights-12` for .env

```
   MANAGER_PSWD=$2b$10$SO7hwwylEnHKZIv68w/ePOK4yybPnhXa5.tQSUBe.PSb6FBKyuVO.
```

- create two Postgres database for development and then test
- run `npm run createTables` to create tables for you

- run `npm run dev-start` to start the server.

- login using existing user credentials POST `localhost:4000/api/v1/auth/login`

```
{
    "email": "alain.maxime@gmail.com",
    "password": "Niyonkuru@1"
}

```
- copy the `user's token` in the following app `https://codepen.io/moise1/pen/jOPYveW`

- make a new request by POST `http://localhost:4000/api/v1/trips/returnTrip`

{
	"origin": "Burundo",
	"destination": "kgl",
	"departureDate": "9002-04-02",
	"returnDate": "9003-05-18",
	"accommodation": "XYZ campus",
	"reason": "Having a meeting",
	"passportNumber": "yuyut56"
}
### - log in as a manager using these credentials:

```
{
    "email": "william.ishimwe@andela.com",
    "password": "Password@1"
    }
```

### Request ID to comment on in the Params tab
Screen Shot 2020-03-10 at 18 01 25

#### Comment in the body tab
Screen Shot 2020-03-10 at 17 59 28

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?

[#170947680](https://www.pivotaltracker.com/story/show/170947680)

### CODE REVIEW

**Review by Niyonsengaeric — APPROVED** [review]
Nice work @Moise1 I think this is ready to be merge.

**Comment by Kagorora** [comment]
@Moise1 As a requester I can successfully see the notification whenever a comment is made by the manager, whoever the reverse thus as a manager I can't see the notification when comment is made by the requester. any ideas?

**Comment by Niyonsengaeric** [comment]
> @Moise1 As a requester I can successfully see the notification whenever a comment is made by the manager, whoever the reverse thus as a manager I can't see the notification when comment is made by the requester. any ideas?

@Kagorora I think as I see in the PT, the notification must be on the side of the requester I think the notification on the side of the manager is another endpoint if I am not wrong!!!

Screen Shot 2020-03-11 at 13 11 05

**Comment by Moise1** [comment]
@Kagorora looking at the story description, though ambiguous, it says that only the requester has to be notified whenever a comment is posted in their request.

**Pull request closed without merging**
