### PR TITLE
#170947677 mark all notifications as read

### PR DESCRIPTION
**Pull request by Niyonsengaeric**
#### What does this PR do?
- Mark all notifications as read.
#### Description of Task to be completed?
- Check if the user is logged in.
- View all his non_read notifications.
- Mark all notifications as read.
- Test the endpoint.
- Document the endpoint using swagger documentation.
#### How should this be manually tested?
- run `git clone https://github.com/andela/knights-bn-backend.git` to clone the repo.
- run `cd knights-bn-backend` in your terminal to enter into the repository.
- run `git checkout ft-mark-all-notifications-as-read-170947677` to switch to this branch.
- run `npm install` to install dependencies.
- create a Postgres database.
- create a .env file then add environment variable as shown below:
```
DB_USER='name of the user of the database'
DB_PASS='password of your Postgres'
DB_NAME='name of the database || Barefoot'
DB_TEST_NAME='name of the database for test || Barefoot_test'
NODE_ENV='development'
SECRETKEY='PrivateKey'
BN_API_KEY='use the SendGrid given ken'
```
- use .env.example as a blueprint for your .env file.
- run `npm run createTables` to create the database tables.
- run `npm dev-start` to start the server.
- open the browser use URL:`http://localhost:4000/api/v1/docs` for swagger documentation.
- Open postman and copy this URL POST `http://localhost:4000/api/v1/auth/login`. to login to the system if you have an account.
- If you don't have an account open postman and copy this URL POST `localhost:4000/api/v1/auth/signup`  to sign up
- Use this format to Sign up
```
{
	"firstName": "Kagorora",
	"lastName": "Messi",
	"gender": "Male",
	"PassportNumber": "12345675",
	"email": "example@gmail.com ",
	"password": "Niyonkuru@1"
}
```
- Use this user to login as manager
```
{
 "email": "william.ishimwe@andela.com",
 "password": "Password@1" 
}
             
```
- If a user is successfully signup or login 
#### View non read notifications
 - Open postman and copy and send this URL GET `http://localhost:4000/api/v1/notifications`.
- You will see your non-read notifications if you have them.
#### Mark all your notifications as read
 - Open postman and copy and send this URL PATCH `http://localhost:4000/api/v1/notifications`.
- All your notification will be marked as read.
- To test it you can again View non-read notifications `GET `http://localhost:4000/api/v1/notifications`
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#170947677](https://www.pivotaltracker.com/story/show/170947677)
#### Screenshots 

                        Logging successful

Screen Shot 2020-03-04 at 17 39 31

             View notification 

Screen Shot 2020-03-04 at 17 44 34

         Mark all as read 

Screen Shot 2020-03-05 at 19 33 41

       Trying to view new notifications again.

Screen Shot 2020-03-04 at 17 35 39

#### Questions:
N/A

### CODE REVIEW

**Comment by Kagorora** [comment]
@Niyonsengaeric I found your response interesting, As when I mark notifications as read, They are no longer visible, Why haven't you made them read and may be display them anyway?

         Before marking notifications as read

Screen Shot 2020-03-05 at 08 17 21


          Mark notification as read

Screen Shot 2020-03-05 at 08 17 31

          View all my notification

Screen Shot 2020-03-05 at 08 21 13

**Comment by Niyonsengaeric** [comment]
@Kagorora, as you are seeing the message `you have no new notification` on the second picture, it means that your notifications have all made read. So you no longer have a non_read notifications.

**Review by Kagorora — APPROVED** [review]

**Review by Moise1 — APPROVED** [review]

**Review by kagabof — CHANGES_REQUESTED** [review]
Please edit your commit message and follower the Andela engineering playbook

**Comment by Niyonsengaeric** [comment]
> Please edit your commit message and follower the Andela engineering playbook

Thank you @kagabof I just change it.

**Pull request merged**
