### PR TITLE
#170947646 Configure eslint

### PR DESCRIPTION
**Pull request by Niyonsengaeric**
#### What does this PR do?
This PR Configures eslint with Airbnb style guide.
#### Description of Task to be completed?
- configure eslint for checking for style violations and flag them
#### How should this be manually tested?
- [clone the repo](https://github.com/andela/knights-bn-backend.git)
- run `npm i` to install the dependencies 
- create a file then start write your code
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#170947646](https://www.pivotaltracker.com/story/show/170947646)

#### Screenshots (if appropriate)
N/A

### CODE REVIEW

**Review by Moise1 — APPROVED** [review]

**Review by EugeneMunya — APPROVED** [review]
LGTM

**Review by T2Wil — DISMISSED** [review]

**Review by MuhanguziDavid — CHANGES_REQUESTED** [review]
Nice work with eslint @Niyonsengaeric , however, it looks like you have squashed into one of the commits on develop (squashed a commit too far). Please rectify this.

**Review by T2Wil — APPROVED** [review]
LGTM

**Review by MuhanguziDavid — APPROVED** [review]
LGTM

**Pull request merged**
